name: Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:
    workflow_call:
        inputs:
            args:
                required: false
                type: string
                description: "Additional arguments for the tests"
                default: ""

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

            - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
              with:
                  path: build/cache
                  key: ${{ runner.os }}-build-tools-cache-${{ hashFiles('build/checksums.txt') }}

            - name: Set up Go
              uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
              with:
                  go-version: 1.26
                  cache: false

            - name: Run tests
              run: go test -short ./...
