name: Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:
    workflow_call:
        inputs:
            args:
                required: false
                type: string
                description: "Additional arguments for the tests"
                default: ""

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231

            - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
              with:
                  path: build/cache
                  key: ${{ runner.os }}-build-tools-cache-${{ hashFiles('build/checksums.txt') }}

            - name: Set up Go
              uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
              with:
                  go-version: 1.26
                  cache: false

            - name: Run tests
              run: go test -short ./...
